In [1]:
import pandas as pd

In [2]:
data = {
    "name": ["Amit", "Riya", "John", "Priya", "Rahul"],
    "age": [23, 25, 21, 24, 22],
    "city": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai"],
    "salary": [50000, 60000, 45000, 52000, 58000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

    name  age     city  salary
0   Amit   23    Delhi   50000
1   Riya   25   Mumbai   60000
2   John   21    Delhi   45000
3  Priya   24  Kolkata   52000
4  Rahul   22   Mumbai   58000

Task 1:

Print first 3 rows

In [5]:
df.head(3)

   name  age    city  salary
0  Amit   23   Delhi   50000
1  Riya   25  Mumbai   60000
2  John   21   Delhi   45000

Task 2:

Select only the "name" column

In [6]:
df["name"]

0     Amit
1     Riya
2     John
3    Priya
4    Rahul
Name: name, dtype: str

In [21]:
df[["name"]].head(3) # -> dataframe
# df["name"].head(3) # -> series

   name
0  Amit
1  Riya
2  John

Task 3:

Filter people whose age > 22

In [10]:
df[df["age"] > 22]

    name  age     city  salary
0   Amit   23    Delhi   50000
1   Riya   25   Mumbai   60000
3  Priya   24  Kolkata   52000

Task 4:

Filter people from "Mumbai"

In [13]:
df[df["city"] == "Mumbai"]

    name  age    city  salary
1   Riya   25  Mumbai   60000
4  Rahul   22  Mumbai   58000

Task 5 (Important ⚡):

Get name and salary of people whose salary > 50000

In [22]:
# df[df["salary"] > 50000][["name", "salary"]]
df.loc[df["salary"] > 50000, ["name", "salary"]]

    name  salary
1   Riya   60000
3  Priya   52000
4  Rahul   58000

🧪 Mini Challenge (Before Day 2)

👉 Get people:

age > 22

AND city = "Mumbai"

Only show: name, age

In [26]:
df.loc[(df["age"] > 22) & (df["city"] == "Mumbai"), ["name", "age"]]

   name  age
1  Riya   25

In [28]:
# (df["age"] > 22) & (df["city"] == "Mumbai")
# THIS IS CALLED BOOLEAN MASKED