In [4]:
import pandas as pd

In [5]:
data = {
    "name": ["Amit", "Riya", "John", "Priya", "Rahul"],
    "age": [23, 25, 21, 24, 22],
    "city": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai"],
    "salary": [50000, 60000, 45000, 52000, 58000]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

    name  age     city  salary
0   Amit   23    Delhi   50000
1   Riya   25   Mumbai   60000
2   John   21    Delhi   45000
3  Priya   24  Kolkata   52000
4  Rahul   22   Mumbai   58000

In [11]:
df["name"], df["name"][0] # indexing will work with series only

(0     Amit
 1     Riya
 2     John
 3    Priya
 4    Rahul
 Name: name, dtype: str,
 'Amit')

In [13]:
df[["name"]] # this is data fram
df["name"] # this is series

0     Amit
1     Riya
2     John
3    Priya
4    Rahul
Name: name, dtype: str

In [33]:
df.loc[0, 'name'], df["name"][0]

# df["name"][0] = Not recommended
# df["name"][0] = because it can break with index changes

# Always prefer = df.loc[0, "name"]

('Amit', 'Amit')

In [18]:
df.iloc[0, 0]

'Amit'

In [19]:
# 🔹 .loc → uses labels (names)
# 🔹 .iloc → uses index (numbers)

Task 1:

Get first row using .iloc

In [21]:
df.iloc[[0]]

   name  age   city  salary
0  Amit   23  Delhi   50000

Task 2:

Get first 2 rows and first 2 columns using .iloc

In [31]:
df.iloc[:2, :2]

   name  age
0  Amit   23
1  Riya   25

Task 3:

Get row with index 3 using .loc

In [25]:
df.loc[[3]]

    name  age     city  salary
3  Priya   24  Kolkata   52000

Task 4:

Get "name" and "city" columns for rows 1 to 3 using .loc

In [28]:
df.loc[1:3, ["name", "city"]]

    name     city
1   Riya   Mumbai
2   John    Delhi
3  Priya  Kolkata

Task 5 (Important ⚡):

Get all rows where:

- age < 24
    Return:
- all columns

(use .loc)

In [30]:
df.loc[df["age"] < 24]

    name  age    city  salary
0   Amit   23   Delhi   50000
2   John   21   Delhi   45000
4  Rahul   22  Mumbai   58000

| Feature      | `.loc`    | `.iloc`   |
| ------------ | --------- | --------- |
| Uses         | Labels    | Index     |
| Range        | Inclusive | Exclusive |
| Safer for ML | ✅         | ⚠️        |