In [13]:
import pandas as pd

In [14]:
data = {
    "name": ["Amit", "Riya", "John", "Priya", "Rahul"],
    "age": [23, 25, 21, 24, 22],
    "city": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai"],
    "salary": [50000, 60000, 45000, 52000, 58000]
}

In [15]:
df = pd.DataFrame(data)

Task 1:

Create a new column:
👉 "bonus" = salary * 10%

In [16]:
df["bonus"] = df["salary"] * .10

In [17]:
df

    name  age     city  salary   bonus
0   Amit   23    Delhi   50000  5000.0
1   Riya   25   Mumbai   60000  6000.0
2   John   21    Delhi   45000  4500.0
3  Priya   24  Kolkata   52000  5200.0
4  Rahul   22   Mumbai   58000  5800.0

Task 2:

Create a new column:
👉 "total_income" = salary + bonus

In [18]:
df["total_income"] = df["salary"] + df["bonus"]

In [19]:
df

    name  age     city  salary   bonus  total_income
0   Amit   23    Delhi   50000  5000.0       55000.0
1   Riya   25   Mumbai   60000  6000.0       66000.0
2   John   21    Delhi   45000  4500.0       49500.0
3  Priya   24  Kolkata   52000  5200.0       57200.0
4  Rahul   22   Mumbai   58000  5800.0       63800.0

Task 3:

Increase salary of people from "Delhi" by 10%

In [20]:
df[df["city"] == 'Delhi']

   name  age   city  salary   bonus  total_income
0  Amit   23  Delhi   50000  5000.0       55000.0
2  John   21  Delhi   45000  4500.0       49500.0

In [21]:
# df["salary"] = df[df["city"] == 'Delhi']['salary'] * .10 = NOT WORKING

df['salary'] = df['salary'].astype(float) # required since it is going to mulitply by float number
df.loc[df['city'] == 'Delhi', 'salary'] *= 1.10

In [22]:
df

    name  age     city   salary   bonus  total_income
0   Amit   23    Delhi  55000.0  5000.0       55000.0
1   Riya   25   Mumbai  60000.0  6000.0       66000.0
2   John   21    Delhi  49500.0  4500.0       49500.0
3  Priya   24  Kolkata  52000.0  5200.0       57200.0
4  Rahul   22   Mumbai  58000.0  5800.0       63800.0

Task 4 (Important ⚡):

Rename column "city" → "location"

In [26]:
df.rename(columns={ "city": "location" }, inplace=True)

In [27]:
df

    name  age location   salary   bonus  total_income
0   Amit   23    Delhi  55000.0  5000.0       55000.0
1   Riya   25   Mumbai  60000.0  6000.0       66000.0
2   John   21    Delhi  49500.0  4500.0       49500.0
3  Priya   24  Kolkata  52000.0  5200.0       57200.0
4  Rahul   22   Mumbai  58000.0  5800.0       63800.0

Task 5 (Advanced 🔥):

Convert all names to uppercase

In [31]:
df["name"] = df["name"].str.upper()

In [32]:
df

    name  age location   salary   bonus  total_income
0   AMIT   23    Delhi  55000.0  5000.0       55000.0
1   RIYA   25   Mumbai  60000.0  6000.0       66000.0
2   JOHN   21    Delhi  49500.0  4500.0       49500.0
3  PRIYA   24  Kolkata  52000.0  5200.0       57200.0
4  RAHUL   22   Mumbai  58000.0  5800.0       63800.0