In [1]:
import pandas as pd

In [2]:
data = {
    "name": ["Amit", "Riya", "John", "Priya", "Rahul"],
    "age": [23, 25, 21, 24, 22],
    "city": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai"],
    "salary": [50000, 60000, 45000, 52000, 58000]
}

In [3]:
df = pd.DataFrame(data)

Task 1:

Sort data by salary (descending)

In [5]:
df.sort_values(["salary"], ascending=False)

    name  age     city  salary
1   Riya   25   Mumbai   60000
4  Rahul   22   Mumbai   58000
3  Priya   24  Kolkata   52000
0   Amit   23    Delhi   50000
2   John   21    Delhi   45000

Task 2:

Find:
- average salary
- max salary
- min salary

In [7]:
df["salary"].mean(), df["salary"].max(), df["salary"].min()

(np.float64(53000.0), np.int64(60000), np.int64(45000))

Task 3:

Count how many people are from each city/location

In [12]:
df.groupby("city").count()

         name  age  salary
city
Delhi       2    2       2
Kolkata     1    1       1
Mumbai      2    2       2

In [13]:
df['city'].value_counts()
df.groupby('city').size()
df['city'].value_counts().reset_index()
df['city'].value_counts().reset_index(name='count').rename(columns={'index': 'city'})
df['city'].value_counts(ascending=True)
df['city'].value_counts(dropna=False)

city
Delhi      2
Mumbai     2
Kolkata    1
Name: count, dtype: int64

Task 4:

Find person with highest salary

In [18]:
df.loc[df["salary"] == df["salary"].max()]
# df.nlargest(1, "salary")

   name  age    city  salary
1  Riya   25  Mumbai   60000

Task 5 (Important ⚡):

Get all people whose salary is above average

In [17]:
df.loc[df["salary"] > df["salary"].mean()]

    name  age    city  salary
1   Riya   25  Mumbai   60000
4  Rahul   22  Mumbai   58000