In [2]:
import pandas as pd

In [3]:
data = {
    "name": ["Amit", "Riya", "John", "Priya", "Rahul"],
    "age": [23, 25, 21, 24, 22],
    "city": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai"],
    "salary": [50000, 60000, 45000, 52000, 58000]
}

In [4]:
df = pd.DataFrame(data)

Task 1:

Find average salary per city

In [5]:
df

    name  age     city  salary
0   Amit   23    Delhi   50000
1   Riya   25   Mumbai   60000
2   John   21    Delhi   45000
3  Priya   24  Kolkata   52000
4  Rahul   22   Mumbai   58000

In [6]:
df.groupby('city')["salary"].mean()

city
Delhi      47500.0
Kolkata    52000.0
Mumbai     59000.0
Name: salary, dtype: float64

Task 2:

Find:

- max salary per city
- min salary per city

In [7]:
df.groupby('city')['salary'].max(), df.groupby('city').min()

(city
 Delhi      50000
 Kolkata    52000
 Mumbai     60000
 Name: salary, dtype: int64,
           name  age  salary
 city
 Delhi     Amit   21   45000
 Kolkata  Priya   24   52000
 Mumbai   Rahul   22   58000)

Task 3:

Find total salary paid per city

In [8]:
df

    name  age     city  salary
0   Amit   23    Delhi   50000
1   Riya   25   Mumbai   60000
2   John   21    Delhi   45000
3  Priya   24  Kolkata   52000
4  Rahul   22   Mumbai   58000

In [9]:
df.groupby("city")["salary"].sum()

city
Delhi       95000
Kolkata     52000
Mumbai     118000
Name: salary, dtype: int64

Task 4 (Important ⚡):

Get multiple aggregations:

👉 For each city:

- avg salary
- max salary
- min salary

In [10]:
df.groupby("city")["salary"].agg(["mean", "max", "min"])

            mean    max    min
city
Delhi    47500.0  50000  45000
Kolkata  52000.0  52000  52000
Mumbai   59000.0  60000  58000

Task 5 (Advanced 🔥):

Find city with highest average salary

In [11]:
c = df.groupby('city')["salary"].mean()
c.idxmax(), c.max()

('Mumbai', np.float64(59000.0))

🚀 Mini Challenge (Before Day 4)

Try this yourself:

👉 Find:

- City with lowest total salary
- Person with lowest salary in that city

In [13]:
c = df.groupby("city")["salary"].min()
city = c.idxmin()
sala = c.min()

city, sala

('Delhi', np.int64(45000))

In [22]:
c = df.groupby('city')["salary"].min()
df[df["salary"] == c.min()]

   name  age   city  salary
2  John   21  Delhi   45000

In [23]:
# df[df["salary"] == df.groupby("city")["salary"].transform("min")]
# df.loc[df.groupby("city")["salary"].idxmin()]
# df[df["salary"] == df["salary"].min()]